### PR TITLE
Use button styling for the button to show closed wikis

### PR DESCRIPTION
**Pull request by MatmaRex**

### CODE REVIEW

**Comment by edg2s** [comment]
I've never been a fan of buttons in line with text, maybe because the alignment never seems quite perfect.

_Before_
image

_After_
image

But if you prefer this, go for it. Code looks fine.

**Comment by edg2s** [comment]
I think this would look better as a warning box, with a right-aligned button:

image

cf GitHub notifications:
image

**Comment by MatmaRex** [comment]
Eh, good enough.

**Comment by MatmaRex** [comment]
(Your proposal also looks okay)

**Pull request merged**
