### PR TITLE
Don't attempt to fetch task metadata if not API key present

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by edg2s** [comment]
Merge after #225

**Comment by MatmaRex** [comment]
Whyyyyyyyyyyyy are there conflicts, it was fine locally

**Comment by MatmaRex** [comment]
Using GitHub for collaborative coding is like pulling teeth, I have no idea how people deal with this on a daily basis. I'd rather take patches by email at this point.

**Comment by edg2s** [comment]
> Using GitHub for collaborative coding is like pulling teeth, I have no idea how people deal with this on a daily basis. I'd rather take patches by email at this point.

I'm so excited about our move to GitLab....

We could move this project to Gerrit?

**Pull request merged**
