### PR TITLE
Add Disambiguator extension

### PR DESCRIPTION
**Pull request by MusikAnimal**
This is deployed to nearly all WMF wikis. Community Tech is actively working on it and it'd be useful to have it available on Patch Demo.

### CODE REVIEW

**Comment by MatmaRex** [comment]
Do you want to add it to the Wikimedia preset too? Otherwise you'll have to toggle it on in the list every time.

You can also add some disambiguations pages, and pages with links to disambiguations pages, to make it easier to test, see <https://github.com/MatmaRex/patchdemo/tree/master/pages>.

**Comment by MatmaRex** [comment]
(I'm happy to merge this as-in, let me know)

**Comment by MusikAnimal** [comment]
> Do you want to add it to the Wikimedia preset too? Otherwise you'll have to toggle it on in the list every time.

It looks like it might already be enabled for the Wikimedia preset: https://github.com/MatmaRex/patchdemo/blob/592a223dc7d0c9fd66ea64aeefafdbd2c19e6366/repositories-preset-wikimedia.txt#L27

> You can also add some disambiguations pages, and pages with links to disambiguations pages, to make it easier to test, see https://github.com/MatmaRex/patchdemo/tree/master/pages.

Very cool! I took a stab at this. Hopefully I did it correctly.

**Comment by MatmaRex** [comment]
Thanks, sorry I made you wait.

**Comment by MusikAnimal** [comment]
@MatmaRex ping in case you missed the last push

**Comment by MusikAnimal** [comment]
> Thanks, sorry I made you wait.

Ha! No worries, but what a coincidence that pinged you the very same second you merged... hehe!

Thanks!

**Comment by MatmaRex** [comment]
Huh, I posted my message and saw your message appear. :D

**Pull request merged**
