### PR TITLE
LS: Update Parsoid config to new system

### PR DESCRIPTION
**Pull request by jdforrester**
This maybe should work?

### CODE REVIEW

**Comment by MatmaRex** [comment]
I haven't merged this yet because I want Patchdemo to work with older release branches too and not just master (note the "Start with version" dropdown). Admittedly I haven't tested that since the first commits in this repo, so it might be broken right now, but I don't want to make it impossible to fix. I need to think about it (or you can think about it if you want and propose a solution ;) ).

**Comment by edg2s** [comment]
Speaking of "start with version": #89

**Comment by MatmaRex** [comment]
Looking at this again: we definitely need to keep at least the `wfLoadExtension( … )` call, to load Parsoid from the Git repo (where we can apply the desired patches) rather than from the Composer library (where we can't). I'm not sure if the config options will magically configure themselves right if we do that, or if we need to keep some of them too.

**Comment by MatmaRex** [comment]
I want Patchdemo to stay compatible at least with the non-EOL MW release versions.

**Pull request closed without merging**
