### PR TITLE
Add API action 'findwikis' to find a wiki by a change number

### PR DESCRIPTION
**Pull request by edg2s**
Part of #285

### CODE REVIEW

**Comment by edg2s** [comment]
Example request/response:
`https://patchdemo.wmflabs.org/api.php?action=findwikis&change=813350`
```json
[
  {
    "wiki":"0483bb0894",
    "creator":"ESanders (WMF)",
    "created":"2022-07-13 15:11:52",
    "url":"https:\/\/patchdemo.wmflabs.org\/wikis\/0483bb0894\/wiki\/Special:UserLogin?returnto=Talk%3ADiscussionTools"
  },
  {
    "wiki":"2ca64449dd",
    "creator":"ESanders (WMF)",
    "created":"2022-07-13 15:13:23",
    "url":"https:\/\/patchdemo.wmflabs.org\/wikis\/2ca64449dd\/wiki\/Special:UserLogin?returnto=Talk%3ADiscussionTools"
  }
]
```

**Comment by hashar** [comment]
Nice! Maybe the `url` should be unescaped in the json response?

If a change has multiple wikis, maybe we would need the list of applied patches to help disambiguates between multiple instances similar to how it is displayed on https://patchdemo.wmflabs.org/

**Comment by edg2s** [comment]
It's much more common that wikis get rebuilt the same set of changes, but just newer patchsets.

**Comment by edg2s** [comment]
> Maybe the `url` should be unescaped in the json response?

This is just PHPs default JSON encoding...
```
php > echo json_encode("a/b");
"a\/b"
```

**Comment by edg2s** [comment]
I've added patch data to the response:
```
[
  {
    "wiki":"0483bb0894",
    "creator":"Ed",
    "created":"2022-07-13 15:11:52",
    "patches":[
      "813350,2"
    ],
    "url":"http:\/\/localhost\/patchdemo\/wikis\/0483bb0894\/wiki\/Special:UserLogin?returnto=Talk%3ADiscussionTools"
  },
  {
    "wiki":"2ca64449dd",
    "creator":"Ed",
    "created":"2022-07-13 15:13:23",
    "patches":[
      "813350,2"
    ],
    "url":"http:\/\/localhost\/patchdemo\/wikis\/2ca64449dd\/wiki\/Special:UserLogin?returnto=Talk%3ADiscussionTools"
  }
]
```

**Comment by edg2s** [comment]
> > Maybe the `url` should be unescaped in the json response?
> 
> This is just PHPs default JSON encoding...
> 
> ```
> php > echo json_encode("a/b");
> "a\/b"
> ```

Apparently there's a flag for this: #541

**Comment by hashar** [comment]
> ```
> php > echo json_encode("a/b");
> "a\/b"
> ```
I am so PHP illiterate nowadays ;)

To disambiguate, I think the instances can be represented with the wiki ids followed by either the change number or task (whatever set has the least items):

| Run | Summary
|---|---
| Patchdemo | ↗️ 0483bb0894  `T123456`
| Patchdemo | ↗️ 2ca64449dd   `888333,43`

Then clicking on one of the line would expand a drop down with some raw text giving more details. There for a single task and multiple patches:
```
Patch demo ↗️ 0483bb0894  `T123456`

993049,39 (merged) Do some stuff
993012,13 Some other things
```

And a single Gerrit change referring to multiple tasks:
```
Patch demo ↗️ 2ca64449dd   `888333,43`

T304943 Fix up foo
🗸T309098 Adjust compatibility for Y
T309099 Adjust compatibility for Z
```

Given the dropdown message is a raw text unfortunately, but that at least gives some informations :)

**Comment by edg2s** [comment]
As above, I don't think this will disambiguate in most cases (also we take the task number from the gerrit description, so there's no new info there). You'd be better off showing the patchset number it was built for on this change, followed by the timestamp:

| Run | Summary
|---|---
| Patchdemo | ↗️ 0483bb0894  `PS3`, 4 days ago
| Patchdemo | ↗️ 2ca64449dd  `PS4`, 2 hours ago
| Patchdemo | ↗️ 449dd2ca64  `PS4`, 10 minutes ago

**Comment by edg2s** [comment]
@hashar this as been deployed

**Comment by hashar** [comment]
In case someone come here in the future, there are some screenshots of the integration in Gerrit at https://phabricator.wikimedia.org/T332474#8874936

**Pull request merged**
