### PR TITLE
Apply patches before running installer

### PR DESCRIPTION
**Pull request by edg2s**
Patches could affect the outcome of the installation
process, e.g. changing extension.json dependencies.

### CODE REVIEW

**Comment by edg2s** [comment]
Not sure why we did things this way around?

Could this remove the need to run update.php in postinstall?

**Comment by MatmaRex** [comment]
I think I wrote it that way before you refactored how wiki creation works, when it was all in one big .sh script and it was more difficult to do it this way.

**Comment by edg2s** [comment]
I wonder if we still need to run the update script after install now?

**Comment by MatmaRex** [comment]
Maybe not, but it seems harmless and maybe even useful to test that path.

**Pull request merged**
