### PR TITLE
Highlight merged/abandoned changes

### PR DESCRIPTION
**Pull request by edg2s**
Part of #14

### CODE REVIEW

**Comment by edg2s** [comment]
Merge after #117

**Comment by edg2s** [comment]
image

**Comment by MatmaRex** [comment]
I merged  #117 and this now says "Base automatically changed from tasks to master 2 minutes ago", so that's nice, but it looks like I still have to manually rebase this, because it's too dumb to do that.

**Comment by edg2s** [comment]
Doesn't appear to be working on live :/

**Comment by edg2s** [comment]
Oh, just a CSS caching issue.

**Pull request merged**
