### PR TITLE
Make installer more user friendly

### PR DESCRIPTION
**Pull request by edg2s**
* Show a progress bar at the top of the page that increments
  with each successful shell command.
* Show any error messages at the top of the page.
* Only give a wiki link when the wiki has been successfully built,
  also show this at the top of the page. Make it a big blue button.
* Apply console styling to the log messages to make it clear they
  are output for technical users.

### CODE REVIEW

**Comment by edg2s** [comment]
Screenshots:
image
image
image

**Comment by jdforrester** [comment]
Nice.

**Comment by iamjessklein** [comment]
Very nice, @edg2s 
I kind of feel like the "When complete ..." sentence is unnecessary.

**Comment by edg2s** [comment]
> Very nice, @edg2s
> I kind of feel like the "When complete ..." sentence is unnecessary.

Probably, I wanted somewhere to put the wiki's hash (the thing in brackets) for advanced users.

Also we need to put the login info somewhere, it might look odd if it was the only label next to the button?

**Pull request merged**
