### PR TITLE
Enable inbox extension for testing emails

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by MatmaRex** [comment]
I was actually just about to click the button here

**Comment by edg2s** [comment]
:) Thought, I'd bundle this with the extension that will use it (although the extension doesn't exist in Gerrit yet), so ... -1

**Comment by MatmaRex** [comment]
Patchdemo actually sends you emails currently (I just tested it, was a bit surprised that it works), so this would have still had an effect. But we can do them together as well.

**Comment by edg2s** [comment]
Interesting, must be a cloud vps thing. Moved to #251.

**Comment by MatmaRex** [comment]
The repo has been imported: https://www.mediawiki.org/w/index.php?title=Gerrit/New_repositories/Requests/Entries&diff=prev&oldid=4427762&diffmode=source

**Pull request merged**
