### PR TITLE
Re-enable PHP CI with PHP 7.4 (not 8)

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Review by jdforrester — APPROVED** [review]

**Comment by edg2s** [comment]
No idea what's going on here, doesn't seem to respect the php-version I'm passing in.

**Comment by jdforrester** [comment]
Do you have to specify it for each step?

**Comment by jdforrester** [comment]
Hmm, try adding a `shivammathur/setup-php@v2` step first, per https://github.com/marketplace/actions/setup-php-action#tada-php-support

**Comment by edg2s** [comment]
Thanks, working now

**Review by jdforrester — APPROVED** [review]

**Pull request merged**
