### PR TITLE
Add stylelint

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by MatmaRex** [comment]
I don't want to spend the rest of my life updating NPM packages weekly… I'd prefer to avoid adding dependencies, and especially dependencies that pull in 250+ (!) other dependencies.

**Comment by edg2s** [comment]
It's only a dev dependency, and you don't have to update that often if you don't want to. (Or at all, I'll keep an eye on the npm packages).

**Comment by edg2s** [comment]
And currently there is no CI so this optional.

**Comment by MatmaRex** [comment]
I don't want you to spend the rest of your life updating the packages, either. Friends don't let friends add dependencies.

**Comment by edg2s** [comment]
Linting is pretty standard across all our projects. I hardly think this is unnecessary.

**Comment by MatmaRex** [comment]
I am already getting warnings whenever I push because "minimist", whatever that is, has a vulnerability. I don't want this in my life. Can we revert this?

```
$ git push --set-upstream origin logo-link                                                    
Counting objects: 3, done.                                                                                             
Delta compression using up to 8 threads.                                                                               
Compressing objects: 100% (3/3), done.                                                                                 
Writing objects: 100% (3/3), 398 bytes | 398.00 KiB/s, done.                                                           
Total 3 (delta 2), reused 0 (delta 0)                                                                                  
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.                                                  
remote:                                                                                                                
remote: Create a pull request for 'logo-link' on GitHub by visiting:                                                   
remote:      https://github.com/MatmaRex/patchdemo/pull/new/logo-link                                                  
remote:                                                                                                                
remote:                                                                                                                
remote:                                                                                                                
remote: GitHub found 1 vulnerability on MatmaRex/patchdemo's default branch (1 moderate). To find out more, visit:     
remote:      https://github.com/MatmaRex/patchdemo/network/alerts                                                      
remote:                                                                                                                
To github.com:MatmaRex/patchdemo.git                                                                                   
 * [new branch]      logo-link -> logo-link                                                                            
Branch 'logo-link' set up to track remote branch 'logo-link' from 'origin'.    
```

**Comment by edg2s** [comment]
What suffering!

**Comment by edg2s** [comment]
You can turn off security warnings in the repo settings:
image

For devDependencies we shouldn't be that concerned.

**Pull request merged**
