### PR TITLE
Remove Stylelint

### PR DESCRIPTION
**Pull request by MatmaRex**
GitHub keeps bugging me about security issues in dependencies of
Stylelint. It has seemingly endless dependencies and seemingly endless
issues in them. It also provides minimal value, and that's being
generous. Let us excise it and salt the earth.

### CODE REVIEW

**Comment by edg2s** [comment]
I think it provides some value. Can you just turn off security warnings either completely of for devDependencies. Our only real dependency is OOUI (which has no other dependencies) and I think we'll know if that gets flagged with a security issue...

**Comment by MatmaRex** [comment]
Yeah but _come on_ though.

**Comment by MatmaRex** [comment]
This would honestly make my day.

**Comment by edg2s** [comment]
I think a lot of the rules are useful, especially for third party contributions. It catches errors, duplicate code and incorrect indentation. The maintenance burden is pretty much zero in addition to eslint.

**Pull request closed without merging**
