### PR TITLE
Move GrowthExperiments help desk somewhere less likely to conflict

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by edg2s** [comment]
Merge after #134 

cc @catrope

**Comment by MatmaRex** [comment]
Seems fine but I'd like @catrope to confirm this works for the team.

(also, needs manual rebase)

**Review by MatmaRex — CHANGES_REQUESTED** [review]
.

**Comment by catrope** [comment]
Looks fine to me. We don't really care what the help desk is called, it has localized names in different languages anyway.

**Comment by edg2s** [comment]
@MatmaRex Good to merge? This appears to have a phantom change request still attached to it.

**Review by MatmaRex — APPROVED** [review]

**Pull request merged**
